### ISSUE TITLE
Cannot download video if RTMP settings is used

### ISSUE THREAD

**Issue by Julien-Blanc** [known-as-bmf/plugin.video.arteplussept#11]
Testing with latest version, playing is fine but downloading doesn’t work. The log says :

    Error Contents: unknown url type: am/tvguide/EUR_DE_FR/062292-001-A_SQ_2_VOF-STF_02023104_MP4-2200_AMM-Tvguide.mp4

This only happens if RTMP is used, not HTTP.

HTTP should be forced when downloading, whatever settings is used for playing.

**Comment by known-as-bmf** [comment]
I'll have a look at this when I have some free time, thanks for the feedback :)

**Comment by known-as-bmf** [comment]
5400dfe should fix it ! 

I think i'll push the change to the official repo when 0.6.0 is around :)
