### ISSUE TITLE
Future feature : Ability to search for specific videos by keyword

### ISSUE THREAD

**Issue by known-as-bmf** [known-as-bmf/plugin.video.arteplussept#13]
Multiple sorting methods may be available for the results (by release date, views, expiraion date)

http://www.arte.tv/guide/fr/programs?q=[query]&sort=[sort_option]

with sort_option = [newest | most_viewed | next_expiring]

**Comment by hstraub** [comment]
Hallo,

do you mean a keyword search in the title or also in other fields?

**Comment by known-as-bmf** [comment]
The search is done automatically (name / description / other metadata) by the service hosted at the URL I provided.

You just have to pass a keyword as the "q" parameter.

A search for the term "pirate" ordered by views would looke like: http://www.arte.tv/guide/fr/programs?q=pirates&sort=most_viewed

**Comment by known-as-bmf** [comment]
There is also a language parameter in the URL's path.

My guess is that valid options are "fr" and "de".

**Comment by hstraub** [comment]
Thanks for the information. In the next time I will test this and come back.

**Comment by known-as-bmf** [comment]
May come soon ! New endpoints include search by word and topic !

**Comment by thomas-ernest** [comment]
Hello @known-as-bmf,

Thank you for the plugin !

I implemented this feature thanks to Arte TV API in version [1.1.5](https://github.com/thomas-ernest/plugin.video.arteplussept/releases/tag/v1.1.5) in my fork.
Feel free to test and close the issue, if it makes the job.
