### ISSUE TITLE
Horizontal Slide Pictures

### ISSUE THREAD

**Issue by paulcezanne2** [known-as-bmf/plugin.video.arteplussept#18]
Hi bmf,
I love your new arte+7 addon but some little thing doesn't work for me: is it possible - because I love to view the mediathek with SLIDES (not LISTS or whatever) - to get the pictures of the movies in a horizontal (16:9) format-style? At the moment I only get compressed pictures of the movies. Looks a a little bit weird. But the app is running and downloading fine. The other arte apps I had these horizontal slide (I don't know how to explain??!), but the still keep crashes. Yours is running fine! :-) besides the slides. ;-)

I tried to find something in your programming code but I didn't find the right spot to change something in order to achieve these uncompressed pictures. Is this possible?

Best, paule.

**Comment by known-as-bmf** [comment]
Hello,

I looked into it and I don't thinks this is possible with the data from the API I'm using without using python image processing directly.

That would mean
- detecting the current thumbnail mode
- cropping all the images
- (saving them temporarly to disk ?)

I think this would induce a non negligible overhead.

I don't think i'll be working on this for now but if anyone is interested in resolving this, fell free to submit a pull request :)

**Comment by paulcezanne2** [comment]
Hello bmf,
thanks for the answer. I am no programmer and if you cannot do it I will have no chance – that's for sure. 
As far as I understand your explanation, you are using a API where the "vertical orientation" of the pictures are fixed and the use of "horizontal orientation" is not possible. I didn't mean to crop and save the pictures. I was hoping that in the "API you are using" is a setting where it doesn't matter if the pictures are in "horizontal" or "vertical" orientation. That's all. Horizontal would be great, because all the other addons are using horizontal orientation (as far as I see).

But thanks a lot for your work. I really appreciate it.
Paule.

**Comment by thomas-ernest** [comment]
Hello @paulcezanne2 ,

Today, the plugin fetch the image from the API and it doesn't aim at manipulating pictures.
Can you kindly close this issue please ? Because nobody has tried to satisfy this request for 7 years already.

Thank you for your understanding.
