### ISSUE TITLE
Kodi hangs/freezes in when using the livestream option..

### ISSUE THREAD

**Issue by sahneschnitte** [known-as-bmf/plugin.video.arteplussept#20]
hi . since one of the last kodi updates ( in January ) in my case the arte-live stream hangs up. 
( so i got to restart the  raspPi.. ) in the left bottom corner there stands sth more or less like 55:54:59 / 55:55:49 ... or so. don t know . is this a known bug from Kodi or the addon ? have other live stream addons from German TV - they function well. also when i want to watch the arte-stream out of another app ( ARD Mediathek ) it starts to hang up . so it could also be a more generell problem of KODI and not just of your plugin. which, btw. is great ! already tried different quality modes of stream - no change in my case. 

greets
Sahneschnitte

**Comment by known-as-bmf** [comment]
Should be fixed in the latest version !!

You can clone master or wait for the official repo to be updated (could take a while ^^)
