### ISSUE TITLE
Show downloaded video

### ISSUE THREAD

**Issue by Ginko-Aloe** [known-as-bmf/plugin.video.arteplussept#25]
Hi,

A little feature request for this awesome addon: ability to know wether a video as already been downloaded. Maybe a tick somewhere in the video list or a change in the contextual menu indicating there's no need to download it again (don't know what the addon API allows).

Thanks already for this (again) awesome addon: just discovered how powerful he is and I can't do without it anymore.

**Comment by known-as-bmf** [comment]
Hey ! 

I've been quite busy the past months, sorry for the delay

This is an interesting feature but I'm not sure how to implement it.

I'm keeping the issue open for now !

**Comment by known-as-bmf** [comment]
Feature removed do avoid potential trial legal problems, sorry
