### ISSUE TITLE
Live stream broken

### ISSUE THREAD

**Issue by frranck** [known-as-bmf/plugin.video.arteplussept#27]
Hi, 
The Live stream is broken for me since a few weeks. 

21:21:39 1222.472290 T:1586484144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/pi/.kodi/addons/plugin.video.arte_tv/default.py", line 379, in <module>
                                                playLiveStream()
                                              File "/home/pi/.kodi/addons/plugin.video.arte_tv/default.py", line 298, in playLiveStream
                                                listitem = xbmcgui.ListItem(path=match[0][0] + match[0][1] + " swfUrl=http://www.arte.tv/flash/mediaplayer/mediaplayer.swf live=1 swfVfy=1")
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by frranck** [comment]
@known-as-bmf Salut, Le probleme est resolu dans ta branche "master" (parsing de l'url du live  data['video']['VSR'][**0**]['VUR'])  mais pas dans la version taggee 0.5.4...

**Comment by known-as-bmf** [comment]
Feature removed, sorry
