### ISSUE TITLE
Can't set download directory, can't download files on Android

### ISSUE THREAD

**Issue by nio101** [known-as-bmf/plugin.video.arteplussept#32]
Hello,

I really like the addon, but on a Zidoo X9S Android box, I can't set the download directory to any local storage (message: check write rights + directory name).
The storage are available as _/storage/..._ pathes. I also tried on the root path, and on various android pathes, but without any luck.

I also tried to set it on a samba path. It worked for directory selection, but when I tried to download, I got an error. In the Kodi log file, I found:

> 10:27:59 T:18446744072980527408   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IOError'>
>                                             Error Contents: (2, 'No such file or directory', u'smb://NIODATACENTER/video2/072324-009_personne_ne_bouge.mp4')
>                                             Traceback (most recent call last):
>                                               File "/storage/emulated/0/Android/data/com.zidoo.zdmc/files/.zdmc/addons/plugin.video.arteplussept/addon.py", line 357, in <module>
>                                                 plugin.run()
>                                               File "/storage/emulated/0/Android/data/com.zidoo.zdmc/files/.zdmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
>                                                 items = self._dispatch(self.request.path)
>                                               File "/storage/emulated/0/Android/data/com.zidoo.zdmc/files/.zdmc/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
>                                                 listitems = view_func(**items)
>                                               File "/storage/emulated/0/Android/data/com.zidoo.zdmc/files/.zdmc/addons/plugin.video.arteplussept/addon.py", line 214, in download_file
>                                                 f = open(os.path.join(download_folder, filename), 'wb')
>                                             IOError: (2, 'No such file or directory', u'smb://NIODATACENTER/video2/072324-009_personne_ne_bouge.mp4')
>                                             -->End of Python script error report<--

Thanks.

**Comment by nio101** [comment]
Ok, got it... Kodi on Android caen only write in Android/data/org.xbmc.kodi/files directory that should have been created on an external device after having run Kodi...

Using this directory allowed me to use the download feature...

Great addon, really, thanks a lot, guys! (^_^)

**Comment by known-as-bmf** [comment]
Feature removed to avoid potential legal problems, sorry
