### ISSUE TITLE
Nothing can be played

### ISSUE THREAD

**Issue by RobTranquillo** [known-as-bmf/plugin.video.arteplussept#33]
This is NixOS (channel: unstable) unsing Kodi 17.4 via [https://github.com/NixOS/nixpkgs/../applications/video/kodi](https://github.com/NixOS/nixpkgs/tree/52cb1df30c0413752a85a9fb01d48c1a3dba69ce/pkgs/applications/video/kodi) and both Arte plugins do not work. But with your plugin i generate a logfile. 

The error while starting any video from Arte (De/720/RTPM/SQ (High)) is:

`
22:09:00.224 T:139891043298624   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x000d, modifier: 0x0                                                                                    
22:09:00.293 T:139891043298624   DEBUG: OnKey: return (0xf00d) pressed, action is Select                                                                                                         
22:09:00.295 T:139891043298624   DEBUG: OnPlayMedia plugin://plugin.video.arteplussept/play/069099-000                                                                                           
22:09:00.297 T:139890646173440   DEBUG: CAnnouncementManager - Announcement: OnAdd from xbmc                                                                                                     
22:09:00.297 T:139890646173440   DEBUG: GOT ANNOUNCEMENT, type: 2, from xbmc, message OnAdd                                                                                                      
22:09:00.300 T:139891043298624   DEBUG: StartScript - calling plugin Arte +7('plugin://plugin.video.arteplussept/play/069099-000','5','')                                                        
22:09:00.300 T:139888930875136   DEBUG: Thread LanguageInvoker start, auto delete: false                                                                                                         
22:09:00.300 T:139888930875136    INFO: initializing python engine.                                                                                                                              
22:09:00.300 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): start processing                                                         
22:09:00.305 T:139888930875136   DEBUG: -->Python Interpreter Initialized<--                                                                                                                     
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): the source file to load is "/home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py"
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): setting the Python path to /home/kodi/.kodi/addons/plugin.video.arteplussept:/home/kodi/.kodi/addons/script.module.requests/lib:/home/kodi/.kodi/addons/script.module.xbmcswift2/lib:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python27.zip:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/plat-linux2:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-tk:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-old:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-dynload:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/site-packages
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): entering source directory /home/kodi/.kodi/addons/plugin.video.arteplussept
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): the source file to load is "/home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py"
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): setting the Python path to /home/kodi/.kodi/addons/plugin.video.arteplussept:/home/kodi/.kodi/addons/script.module.requests/lib:/home/kodi/.kodi/addons/script.module.xbmcswift2/lib:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python27.zip:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/plat-linux2:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-tk:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-old:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/lib-dynload:/nix/store/2b0p2i97187r6d9nig4hl0xw827j1i5l-python-2.7.13/lib/python2.7/site-packages
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): entering source directory /home/kodi/.kodi/addons/plugin.video.arteplussept
22:09:00.305 T:139888930875136   DEBUG: CPythonInvoker(11, /home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py): instantiating addon using automatically obtained id of "plugin.video.arteplussept" dependent on version 2.14.0 of the xbmc.python api
22:09:00.320 T:139889025373952   DEBUG: Thread scriptobs start, auto delete: false
22:09:00.353 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/" named "index" pointing to function "index"
22:09:00.353 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/listing" named "listing" pointing to function "show_listing"
22:09:00.353 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/dates" named "dates" pointing to function "show_dates"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/categories" named "categories" pointing to function "show_categories"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/play/<vid>" named "play" pointing to function "play"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/enqueue/<vid>" named "enqueue" pointing to function "enqueue"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/download/<vid>" named "download" pointing to function "download_file"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Adding url rule "/live" named "live" pointing to function "play_live"
22:09:00.354 T:139888930875136   DEBUG: [xbmcswift2] Handling incoming request for /play/069099-000
22:09:00.355 T:139888930875136  NOTICE: [xbmcswift2] Request for "/play/069099-000" matches rule for function "play"
22:09:00.469 T:139888930875136   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py", line 357, in <module>
                                                plugin.run()
                                              File "/home/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 332, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/kodi/.kodi/addons/script.module.xbmcswift2/lib/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py", line 200, in play
                                                return plugin.set_resolved_url(create_video(vid))
                                              File "/home/kodi/.kodi/addons/plugin.video.arteplussept/addon.py", line 313, in create_video
                                                'path': video['url'],
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
                                            -->End of Python script error report<--
22:09:00.483 T:139888930875136    INFO: Python script stopped
22:09:00.483 T:139888930875136   DEBUG: Thread LanguageInvoker 139888930875136 terminating
22:09:00.501 T:139889025373952   DEBUG: Thread scriptobs 139889025373952 terminating
22:09:00.501 T:139891043298624   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.arteplussept/play/069099-000]
22:09:00.501 T:139891043298624   DEBUG: Playlist Player: no more playable items... aborting playback
22:09:00.501 T:139889025373952   DEBUG: Thread BackgroundLoader start, auto delete: false
22:09:00.502 T:139891043298624   DEBUG: Keyboard: scancode: 0x24, sym: 0x000d, unicode: 0x0000, modifier: 0x0
22:09:00.509 T:139891043298624   DEBUG: ------ Window Init (DialogNotification.xml) ------
22:09:00.509 T:139891043298624   DEBUG: Window DialogNotification.xml was already loaded
22:09:00.509 T:139891043298624   DEBUG: Alloc resources: 0.00ms
22:09:00.518 T:139889025373952   DEBUG: Thread BackgroundLoader 139889025373952 terminating
`

**Comment by known-as-bmf** [comment]
Still not working ?

**Comment by RobTranquillo** [comment]
Works right now. Thank you very much.

But the plugin has to be uninstalled and reinstalled to get the newest update.
