### ISSUE TITLE
original version?

### ISSUE THREAD

**Issue by Laucha** [known-as-bmf/plugin.video.arteplussept#43]
Hi,

Before, on the 0.5.8 version of the add-on, it was offer the possibility to chose "Préférer les versions originales" ("prefer original versions" I suppose it could be in English) on the settings.
Unfortunately, this option is not more available on the version 1.0.0.
I would like to know if is it possible to put back. Thank!

**Comment by known-as-bmf** [comment]
I'm looking into it 👍

**Comment by llbstr** [comment]
First thanks for the addon, it's one of my favorite on my kodi box. I have the 1.0.2 version but I can't find a way to change the audio stream to original, it's not in my addon settings and playback has only one stream (I use the FR language as an addon option). Maybe I'm missing something, am I?  Thanks!

**Comment by Vinnythetrue** [comment]
I tried to achieve this, I made a pull request.
It seems to work on my end, at least in French language configured

**Comment by ieronimus** [comment]
Salut,
Firstly, thanks for the addon, really useful.
I am not able to choose an "original" version of a movie. is there a way to do it?

**Comment by Vinnythetrue** [comment]
Hello,

Are you speaking about my pull request on the arteplussept kodi addon ? 
https://github.com/known-as-bmf/plugin.video.arteplussept/pull/60
Yu wrote "salut", if you're french, feel free to speak in french to me 
because I'm french :)

So, my modifications should add a new option labelled "VOST" when kodi 
is configured in french, "subbed original version" in other languages. 
When activated the plugin should prioritize original subbed version if 
any exists. The filtering tries to priorities according to the language 
set in kodi in order to select the right subbed video version.

What exactly did you do/try ?

Vinny


Le 2020-06-22 14:50, ieronimus a écrit :

**Comment by known-as-bmf** [comment]
Hello and sorry for the delay.

I just pushed some changes on `master` implementing a switch in the settings for specific video stream selection:

![image](https://user-images.githubusercontent.com/11721166/86034763-795a0180-ba3b-11ea-9370-805f348e07ad.png)

when the option is active, a click on a video will open a new menu:

![image](https://user-images.githubusercontent.com/11721166/86034672-5c253300-ba3b-11ea-84fd-c3b3b9b83668.png)

You can test it by manually installing the plugin from the master branch

**Comment by ieronimus** [comment]
Salut Vinny,

merci pour cet update. je ne suis pas chez moi ce week end mais je testerai
semaine prochaine.
quand tu parles de master, cela signifie que je dois faire un download
depuis Github et non une mise à jour depuis Kodi?

cordialement,

Jérôme

Le lun. 29 juin 2020 à 19:07, known-as-bmf <notifications@github.com> a
écrit :

**Comment by known-as-bmf** [comment]
@ieronimus j'ai commit les modifications sur le repo Git mais je n'ai pas encore publié de nouvelle version de l'addon sur Kodi.

Les instructions d'installation manuelle se trouvent [dans le README](https://github.com/known-as-bmf/plugin.video.arteplussept/blob/master/README.md#manual-installation).

**Comment by ieronimus** [comment]
Merci Vinny, cela marche impeccable. Un vrai plus!

Le dim. 5 juil. 2020 à 18:16, known-as-bmf <notifications@github.com> a
écrit :

**Comment by ieronimus** [comment]
Une chose qui me surprend dans cet addon est le fait que soient contournées
les restrictions géographiques d'Arte. Etant en Belgique, certains films ne
sont pas disponibles en replay sur l'app officielle d'Arte.
Mais pas le cas avec l'Addon. Aurais tu une explication?

cordialement,

Le mar. 7 juil. 2020 à 02:32, Jerome Le Tourneur <jeromelt@gmail.com> a
écrit :

**Comment by known-as-bmf** [comment]
@ieronimus  Juste pour information, je ne suis pas @Vinnythetrue  😉 

J'imagine que ces limitations ne concernent pas les API que j'interroge ou alors qu'elles sont implémentées côté client.
