### ISSUE TITLE
arte +7 not in the basic add-on list

### ISSUE THREAD

**Issue by TheAnoyingGuy** [known-as-bmf/plugin.video.arteplussept#50]
'Arte +7' is not in the list of the video add-ons in a default install on Debian!
Why? I checked for a reason over Internet and I can't find any!
Can you explain this choice? It was the only functional add-on for Arte!

**Comment by known-as-bmf** [comment]
It should be available on all version >= Gotham

Which one do you use ?

**Comment by known-as-bmf** [comment]
https://www.howtogeek.com/76240/the-how-to-geek-guide-to-xbmc-add-ons/

Here's a guide just in case 👍

**Comment by TheAnoyingGuy** [comment]
I'm not 100% sure to be honest. My debian is a live OS:
#uname -a: Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
And I'm just following the install kodi on Debian wiki:
https://kodi.wiki/view/HOW-TO:Install_Kodi_for_Linux
Then when I'm looking for arte +7 in the video add-on list it's just not present...
And by the way, thank you for bringing this add-on to life! I'm French and leaving in a foreign country, so this is just really appreciated!!!...

**Comment by TheAnoyingGuy** [comment]
#kodi -v
16.1 Debian package version: 16.1+dfsg1-2~bpo8+2 Media Center Kodi from Debian
Copyright (C) 2005-2013 Team Kodi from Debian - http://kodi.tv

**Comment by known-as-bmf** [comment]
You can usually see the version on the launch screen, below the Kodi logo

Honestly, I don't see why it wouldn't show. Can you attach a screencap of the plugin list ?

**Comment by TheAnoyingGuy** [comment]
This add-on was in the list not even 1 month ago... So I really don't know what happen!!!
The only other add-on related to Arte is a dodgy un-functional one: arte.tv
I do believe that it have nothing to do with you to be honest. Most probably the Main kodi package was updated and they just remove your add-on... Maybe they were planning to remove the dodgy one, and... EPIC fail on their side occurred....
(I'm joining a screenshot of the add-on list I can see via kodi default install)
![screenshot from 2018-06-11 20 28 32](https://user-images.githubusercontent.com/40180933/41252723-8ae9b5ee-6dad-11e8-918a-7ef7210ea29e.png)

**Comment by TheAnoyingGuy** [comment]
:face-palm: Sorry:
![screenshot from 2018-06-11 20 35 33](https://user-images.githubusercontent.com/40180933/41252903-19c98e1a-6dae-11e8-9d93-7f8cacc4fb93.png)

**Comment by known-as-bmf** [comment]
I have no idea why it is not showing up, sorry ☹️

I can give you the instructions to install it manually tomorrow if you want

**Comment by TheAnoyingGuy** [comment]
No problem! Thank you for your time anyway!
I will try to reboot my sys and reinstall everything from scratch again...
But honestly, I think that your plug-in have been removed from the default rep.
And this is really sad! 
By the way I tried to install it manually without success.
I followed the following how to:
https://github.com/known-as-bmf/plugin.video.arteplussept/blob/master/README.md
In any cases: Thank you very much for your time and you effort for this plug-in!

**Comment by TheAnoyingGuy** [comment]
Sorry, I forgot to ask you. Should I close this issue or do you want to continue to investigate it?

**Comment by known-as-bmf** [comment]
Leave it open for now 👍

**Comment by known-as-bmf** [comment]
I would advise you to upgrade kodi to at least 17.2 because of [this issue](https://kodi.tv/article/kodi-v172-minor-bug-fix-and-security-release).

**Comment by known-as-bmf** [comment]
Ok, I now know why it is not showing up.

One of the dependecies I use is not compatible with Kodi 16.1

You can see it by yourself by doing this

![screenshot000](https://user-images.githubusercontent.com/11721166/41305855-7d77cf0a-6e74-11e8-8863-230f1290ed69.png)

![screenshot001](https://user-images.githubusercontent.com/11721166/41305862-817cf10c-6e74-11e8-9701-b1a4ef411922.png)

![screenshot002](https://user-images.githubusercontent.com/11721166/41305865-83b85b28-6e74-11e8-8ef1-e0f95b9395c4.png)

![screenshot003](https://user-images.githubusercontent.com/11721166/41305870-8592b33a-6e74-11e8-9969-944142b4c4ff.png)

My advice to you is upgrading to Kodi 17.6 😅

**Comment by TheAnoyingGuy** [comment]
Nice catch!!!!
All right then... I will have to wait for Kodi to be updated in the debian-backports repository...
Or I will have to stop being lazy and install it manually myself...... 
In any cases thx for your time and your help!!!
And above all, thx for this add-on! (even if I can't use it for now...)
