### ISSUE TITLE
All available Arte+7 videos in a single list

### ISSUE THREAD

**Issue by Grotox** [known-as-bmf/plugin.video.arteplussept#52]
Hi,
I use your plugin for years on a RaspberiPi (with Kodi). I'm veru grateful for that. Thank you.
But it seems that the plugin cannot show all available Arte videos anymore. Is it right?
As I watch Arte every day, I prefer to see all videos ordered by date (most recent first) but I can't find this list anymore. Instead there are many categories with subcategories, making it a long time to browse them all. When I try to get access to the entire list of recent Arte videos, I have the following error: 
```
14:02:30.884 T:1925405184   ERROR: GetDirectory - Error getting plugin://plugin.video.arteplussept/all
14:02:30.890 T:1925405184   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.arteplussept/all) failed
```
[kodi.log](https://github.com/known-as-bmf/plugin.video.arteplussept/files/2102255/kodi.log)

Do you know how I could have access to this 'all' videos list?
Thank you in advance for your help.

**Comment by warfred** [comment]
Hi,
i think i fixed this problem ( D-7 program list w/o clip/trailer and duplicate entries ) but i don´t know how to commit since there is already an active branch for the issue #52.
Has someone an advice how to contribute correctly ?

**Comment by gmahe** [comment]
Maybe you could raise a pull request and wait for someone to review it.

**Comment by Grotox** [comment]
Wow, that's a good news!  :)
@gmahe is right. You could try that.
As you noticed it, a commit has been done about the issue #52 by @known-as-bmf . Maybe yoy could contact him if he's working on it.
I'd be so glad if the "all videos" list is available again!

**Comment by known-as-bmf** [comment]
I pushed a new version to the store that adds a D-7 feature (called "Semaine I18N" for now)

**Comment by known-as-bmf** [comment]
New version was merged earlier today, should be available on the official repo soon.

Go into the "information" page of the addon and make sure that:
* auto-update is enabled
![image](https://user-images.githubusercontent.com/11721166/47917097-b659a380-dea8-11e8-96ad-94ac4fc6f484.png)
* kodi uses the version from the offical repo in the "update" button
![image](https://user-images.githubusercontent.com/11721166/47917210-0a648800-dea9-11e8-96aa-8e0b4266841d.png)

**Comment by Grotox** [comment]
Great! It works perfectly. I'm so greatful I would kiss you!  J
Thank you very much.

**Comment by thomas-ernest** [comment]
Hello @Grotox ,
Can you kindly close the issue, since you mentioned it is working.
Thank you.

**Comment by ze-big-ant** [comment]
Oups. Of course. Sorry.
