### ISSUE TITLE
Plugin only works if the language is set to "fr" after the most recent commit.

### ISSUE THREAD

**Issue by goggle** [known-as-bmf/plugin.video.arteplussept#54]
Hello,

The most recent commit https://github.com/known-as-bmf/plugin.video.arteplussept/commit/92e89d0119f1e1202c2f896861dd843a857487ab breaks the plugin. It only works if the language for the videos in the settings is set to "fr". For other language settings (e.g. "de"), there are no categories shown the main menu and also no videos listed.

Can this be reverted or fixed?

**Comment by known-as-bmf** [comment]
Should be fixed in version 1.0.2

It will be available in the official repo soon.

**Comment by goggle** [comment]
It seems to be working again, thanks for fixing this!
