### ISSUE TITLE
The dependency script.module.xbmcswift2 seems to be deprecated.

### ISSUE THREAD

**Issue by goggle** [known-as-bmf/plugin.video.arteplussept#56]
This addon still relies on the module script.module.xbmcswift2, which was not updated since 2013. I guess that module won't be developed any further.

Are there any plans to drop script.module.xbmcswift2 as a dependency for this addon?

**Comment by known-as-bmf** [comment]
You are right, it's a very nice framework but unfortunately unsupported.

We could switch to something better in the future but for now, I have no plan to remove it.

If you have leads for a replacement, I'm listening :)

**Comment by thomas-ernest** [comment]
xbmcswift2 benefited from updates between 2019-2021 https://github.com/XBMC-Addons/script.module.xbmcswift2/commits/matrix

The plugin uses one of these latest versions (version 19.0.4 https://github.com/known-as-bmf/plugin.video.arteplussept/blob/master/addon.xml#L5)

@goggle ? Do you think you can close the issue please ? I am wondering what issue would solve another framework please ? If it was only the missing support, it seems that community brought the support. :)
