### ISSUE TITLE
ADD ability to see movie in original version

### ISSUE THREAD

**Issue by jerome-m** [known-as-bmf/plugin.video.arteplussept#6]
would it be possible to see a film in original version with subtitles ?

**Comment by known-as-bmf** [comment]
Thanks for the feedback, I will look into it as soon as possible

**Comment by jerome-m** [comment]
Thanks ! Are you french ?

I searched a little, I think it's possible because we can do it with a
browser, so the protocol should handle that.

Have a nice day

J

2015-05-29 9:08 GMT+02:00 known-as-bmf <notifications@github.com>:

**Comment by known-as-bmf** [comment]
Are you sure it is possible to do it through the browser ?

Found a FAQ [[fr](http://videos.arte.tv/fr/videos/index--3581384.html)] [[de](http://videos.arte.tv/de/videos/index--3581384.html)] that says :

```
Peut-on voir les programmes en VO ?

Les programmes sont proposés sur ARTE+7 tels qu’ils ont été diffusés à l’antenne. La plupart du temps, nous diffusons les versions doublées en français ou en allemand.
```

```
Kann man die Programme in der Originalfassung sehen?

Die Programme auf ARTE+7 sind in der Fassung der Fernsehausstrahlung in ARTE abrufbar. Meist werden die französischen oder deutschen Synchronfassungen ausgestrahlt.
```

**Comment by jerome-m** [comment]
Yes !!

**Comment by known-as-bmf** [comment]
Take X:enius for example. The original version is in german.

You can watch it in [german](http://www.arte.tv/guide/de/057372-007/x-enius) or [dubbed in french](http://www.arte.tv/guide/fr/057372-007/x-enius). I think those are the only two options available through Arte +7.

If I understand correctly, the feature you want is to be able to watch it in german subtitled in french ?

**Comment by known-as-bmf** [comment]
Oh sorry, you were taklking about movies like [this one](http://arte.tv/guide/fr/plus7/par_themes?em=000392-000) where you can select VOSTFR.

I'll see what i can do !

**Comment by jerome-m** [comment]
Great !

**Comment by known-as-bmf** [comment]
Done ! You can go in the settings and check the option :)

**Comment by jerome-m** [comment]
Great ! It works perfectly and it's really a plus !
Thanks a lot !! The option by default is nice and I think it's a good choice of ergonomy, would it be possible to switch of version directly by the sound menu in the player (avoiding return to settings)  ?

**Comment by known-as-bmf** [comment]
I looked it up but I don't think that's possible. I'll keep it in mind and implement it if I come across new information.

Also, I posted an experimental plugin to browse Video subreddits [here](https://github.com/known-as-bmf/plugin.video.koddit), you should check it out !
