### ISSUE TITLE
Possibility to download Arte+7 mp4 stream on the device ?

### ISSUE THREAD

**Issue by croisez** [known-as-bmf/plugin.video.arteplussept#63]
Hello,
thanks for this awesome plugin.
I remind some years ago having the possibility to save Arte+7 video on my device for offline viewing.
I don't see this feature anymore.
How could I do this, if this is possible?

**Comment by gmahe** [comment]
No it's long gone, you have to use an older version for that and block the auto-update

**Comment by croisez** [comment]
thanks for the response.
And BTW, does the latest Arte API ( rel. to issue #35 ) still support downloading files ?

**Comment by known-as-bmf** [comment]
Addressed here: https://github.com/known-as-bmf/plugin.video.arteplussept/issues/53#issuecomment-435379133
