### ISSUE TITLE
Feature request (Play the Live tv stream)

### ISSUE THREAD

**Issue by cmakfr** [known-as-bmf/plugin.video.arteplussept#67]
is it possible to play the live tv stream ?

https://www.arte.tv/fr/direct/

**Comment by thomas-ernest** [comment]
Hello @cmakfr 
I implemented this feature in the latest version in my fork (currently [v1.1.5](https://github.com/thomas-ernest/plugin.video.arteplussept)).
Can you kindly try it and close this issue if ok for you ?
Thank you
