### ISSUE TITLE
Only few videos aviable (and random)

### ISSUE THREAD

**Issue by clavierp** [known-as-bmf/plugin.video.arteplussept#68]
Hello,
for few weeks, the plugin doesn't return all available videos. For instance, /arte+7/Serie et Fiction/La Serie du Moment/Kidnapping is empty (only ..). But some are available
The install is brand new (fresh install done) for libreelec, kodi and the plugin.
Kodi is running on rpi2b, locale is FR.

Thank you (for your plugin and your work)!

**Comment by clavierp** [comment]
No erros on kodi.log:

> 2020-10-18 14:35:33.630 T:1470342016  NOTICE: [xbmcswift2] Request for "/sub_category/SER/Les+s%3Fries+du+moment" matches rule for function "sub_category_by_title"
> 2020-10-18 14:35:38.338 T:1362961280  NOTICE: [xbmcswift2] Request for "/collection/TV_SERIES/RC-019890" matches rule for function "collection"

**Comment by known-as-bmf** [comment]
Bonjour et merci pour ce retour !

Les points d'api arte ont encore un peu évolué.

Je viens de pousser un quick fix mais il faudra que vous fassiez une installation manuelle de l'addon pour en tirer parti.

Je dois release une nouvelle version de l'addon sur le repo officiel mais je suis un peu perdu avec leur process de release.

**Comment by known-as-bmf** [comment]
https://github.com/known-as-bmf/plugin.video.arteplussept#manual-installation

**Comment by clavierp** [comment]
Bonjour, tout fonctionne bien. Merci :smiley:

**Comment by clavierp** [comment]
Les endpoints semblent avoir encore bougé.

**Comment by known-as-bmf** [comment]
Un exemple de ce qui ne marche pas ? J'ai l'impression que ça fonctionne de mon côté.
