### ISSUE TITLE
Can't access multiple seasons

### ISSUE THREAD

**Issue by sgiraudot** [known-as-bmf/plugin.video.arteplussept#69]
I can't seem to access multiple seasons of a TV show: for example, if I go to _Inside No 9_, I only have a menu to the 6 episodes of the first season, but I can't see anything else, whereas Arte TV offers the 4 first seasons.

I'm using the `master` version of the plugin.

(And by the way, thanks a lot for this plugin, it's really good and helpful!)

**Comment by known-as-bmf** [comment]
Hello and thank you for your feedback

You should try the latest master version (commit 9c9f1bf0575aaae73cdc4a69d04d301adfd19512)

**Comment by sgiraudot** [comment]
Works like a charm, thanks a lot for the quick fix!
