### ISSUE TITLE
nothing in series folder

### ISSUE THREAD

**Issue by abGBM** [known-as-bmf/plugin.video.arteplussept#71]
Hello,

While using Arte+7 and browsing to "Series et fictions" I can see series sub folder but then folder with series name but there is no episode in each of the folders.
I do not have this behaviour in other categories (Film, news, concert, ...), I am guessing this happens only for series where there are several videos in a folder

Did you know this behavior ?
Thanks

**Comment by known-as-bmf** [comment]
Did you try manually installing the latest version of the add-on from the
GitHub repository (master branch) ?

It could resolve the issue.

**Comment by abGBM** [comment]
Hi,

thanks, it worked !
