### ISSUE TITLE
App automatically disabled after kodi update

### ISSUE THREAD

**Issue by fatcode01** [known-as-bmf/plugin.video.arteplussept#72]
Version 1.0.2 
kodi updated to version 19.0

**Comment by bkuhls** [comment]
This addon, written in python2, is not compatible with kodi 19.0 which requires python3: https://github.com/xbmc/xbmc/pull/16787

**Comment by known-as-bmf** [comment]
I will be updating the add-on later today (UTC+2 timezone).

**Comment by known-as-bmf** [comment]
Updated the add-on to version 1.1.0 and made a pull request to the official add-on repository (matrix only) here https://github.com/xbmc/repo-plugins/pull/3384.

Waiting for the PR to be merged.

**Comment by known-as-bmf** [comment]
PR has been merged into matrix branch, the add-on should appear in the official repo very soon.
