### ISSUE TITLE
Inconsistent licensing data

### ISSUE THREAD

**Issue by felgru** [known-as-bmf/plugin.video.arteplussept#8]
addon.xml and LICENSE.txt mention GPL v2 (or later), but addon.py mentions GPL v3 (or later). I don't know which license you intended to use, but you should probably make those three aforementioned places consistently refer to either GPL v2 or v3 (or later).

**Comment by known-as-bmf** [comment]
Thanks for pointing this out !!

Fixed in d869071cce5171fe6f70606c66d585c5a5dcfe19
