### ISSUE TITLE
Can't download and save videos --No entry in the context menu

### ISSUE THREAD

**Issue by ThZiegler** [known-as-bmf/plugin.video.arteplussept#9]
Hi,

just tried the plugin v0.4 under OSXM, a raspberry version of kodi.

If selecting a video, I can't see a 'download' button in the context menu. There is only
"Wiedergeben", "Besetzung", "Aktualisieren" greyed out, and "Grafik wählen", which translates to s.th. like
"Playback", "Casting", "Actulalize", and "Select Graphics".

There are no Arte+7 specific entries in kodi.log. I've selected a local download folder /tmp/Arte/ in the configuration menu of the plugin.

Watching VOD and life works. Any hints?

Thanks,
Thomas

**Comment by known-as-bmf** [comment]
Hi there and sorry for the delay,

I have no idea why this is happening.

My guess is that the version of Kodi you are using doesn't use the "standard" context menu (I am not familiar with the items you listed) and the framework I use to add context menu entries fails to add them.

I'm afraid I can't do much about that :(

**Comment by known-as-bmf** [comment]
Feature removed to avoid potential legal issues, sorry
